### ISSUE TITLE
Organize Repo into a multi-file structure

### ISSUE THREAD

**Issue by anthonymagari3** [luna-oley/Statistics-Playground#3]
1) Rename Hello_world.py to  processor.py
2) Create folder for each branch of functionality, data_input, data_handling, and data_storage.
3) In each folder we will create a input.py, handling.py, and storage.py
4) Add a unique function in each to print out some statement. (Ensure that our linking is good in the main function)
5) In processor.py we will add a main function to run all of the functions established in step 4.

**Comment by luna-oley** [comment]
I figured out how to add them to the file I am not sure how to link the file to processor.py
